#!/usr/bin/env php
<?php
declare(strict_types=1);

/**
 * Merge the JSON files written by db-behavior-probe.php --json into one markdown
 * comparison. Identical answers collapse to one line per probe, so the report reads
 * as "who differs" instead of a per-server grid.
 *
 *     php .github/scripts/db-behavior-merge.php probes/*.json
 *     php .github/scripts/db-behavior-merge.php probes/*.json >> "$GITHUB_STEP_SUMMARY"
 *     php .github/scripts/db-behavior-merge.php probes/<artifact>/probe-*.json > docs/internal/db-behavior-matrix.md
 */

require __DIR__ . '/ci-lib.php';

if ($argc < 2) {
    fwrite(STDERR, "Usage: php .github/scripts/db-behavior-merge.php <probe.json> [probe2.json ...]\n");
    exit(1);
}

// server => [probe => value], ordered mysql, mariadb, percona, each oldest version first
$reports = [];
foreach (array_slice($argv, 1) as $path) {
    $report = is_file($path) ? json_decode(file_get_contents($path), true) : null;
    if (isset($report['server'], $report['probes'])) {
        $reports[$report['server']] = $report['probes'];
    } else {
        fwrite(STDERR, "Skipping $path: not a db-behavior-probe JSON file\n");
    }
}
uksort($reports, fn($a, $b) => databaseSortKey($a) <=> databaseSortKey($b));

if (!$reports) {
    echo "# DB Behavior Matrix\n\nNo probe data found.\n";
    exit;
}

$families = serverFamilies(array_keys($reports));

echo "# DB Behavior Matrix\n\n";
echo "How every supported database server answers the same behavior probes, showing only where servers disagree. ";
echo "Generated by the \"DB Behavior Matrix\" workflow (.github/workflows/db-behavior-matrix.yml); regenerate with:\n\n";
echo "    gh workflow run db-behavior-matrix.yml   # wait for the run to finish, then:\n";
echo "    gh run download --dir probes             # pick the latest DB Behavior Matrix run\n";
echo "    php .github/scripts/db-behavior-merge.php probes/*/probe-*.json > docs/internal/db-behavior-matrix.md\n\n";
echo "Last generated: " . date('Y-m-d') . " from " . count($reports) . " servers: " . implode(', ', array_keys($reports)) . "\n\n";
echo "Generated file - don't hand-edit. The \"Key differences\" summary below is maintained in the heredoc in .github/scripts/db-behavior-merge.php; edit it there.\n\n";
echo "Stock Docker images with default configs answered these probes. Install-dependent rows ";
echo "(directory paths, sql_mode, TLS and log settings, version strings) will differ on real servers, ";
echo "where distro packages, hosting panels, and my.cnf all change them. SHOW CREATE formatting, ";
echo "error codes, collations, and result typing are fixed per server version.\n\n";

// Curated summary - update by hand when the probe data changes
echo <<<__SUMMARY__
    ## Key differences

    - Percona Server answers every probe byte-identically to the same MySQL version except the version-string probes (its build suffix); nothing else needs separate handling
    - TLS: session status Ssl_cipher/Ssl_version exist on every server and are empty exactly when the connection is unencrypted - the only signal that works everywhere. The variables all have holes: `@@have_ssl` was removed in MySQL/Percona 8.4 and reads DISABLED on stock MariaDB thru 10.11 but YES on MariaDB 11.4+ (auto-generated certs); `@@tls_version` is missing on MariaDB thru 10.3; `@@require_secure_transport` is missing on MariaDB thru 10.4
    - Every version source agrees: server_info matches VERSION() byte-for-byte, and mysqlnd's server_version int matches to the patch level (Percona's build suffix dropped correctly) - though that int is a client-side parse, and PHP before 8.0.16/8.1.3 misread MariaDB's `5.5.5-` handshake prefix as 50505 (php-src GH-7972)
    - SHOW CREATE splits by vendor: MySQL quotes defaults (`'0'`) and prints `CURRENT_TIMESTAMP`; MariaDB prints typed literals (`0`) and `current_timestamp()`, and keeps int display widths (`int(11)`) that MySQL 8.0+ dropped
    - CHECK constraints MySQL/Percona 5.7 can parse (table-level and inline column CHECKs) are silently ignored there; named column CHECKs are 1064 syntax errors on 5.7. Enforced everywhere else, with different error codes (MySQL 3819, MariaDB 4025) and different SHOW CREATE placement (MySQL hoists column CHECKs into named constraints, MariaDB keeps them inline)
    - CHECK lifecycle splits: ADD CONSTRAINT / DROP CONSTRAINT is the one add/drop pair every 8.0.16+ and MariaDB server accepts (DROP CHECK and NOT ENFORCED are MySQL-only). MODIFY COLUMN with an inline CHECK accumulates duplicate auto-named constraints on MySQL 8.0+ but replaces the column's CHECK on MariaDB, where it also can't be dropped by name. Renaming a column a CHECK references is rejected on MySQL 8.0+ (error 3959) but auto-rewrites the expression on MariaDB 10.3+ (10.2 rejects with error 1054); DROP COLUMN silently deletes a single-column CHECK on both
    - Default utf8mb4 collation splits four ways: none stated (MySQL/Percona 5.7 and MariaDB thru 10.2), 0900_ai_ci (MySQL/Percona 8.0+), general_ci (MariaDB 10.3-10.11), uca1400_ai_ci (MariaDB 11.4+)
    - MariaDB 11.4+ lists temporary tables in SHOW TABLES and INFORMATION_SCHEMA.TABLES; every other server hides them
    - Bare TIMESTAMP columns get implicit DEFAULT CURRENT_TIMESTAMP ON UPDATE on MySQL/Percona 5.7 and MariaDB thru 10.6, but stay plain nullable on MySQL/Percona 8.0+ and MariaDB 10.11+ (explicit_defaults_for_timestamp default changed)
    - Time zone offsets beyond -12:59..+13:00 are accepted only by MySQL/Percona 8.0+ (widened in MySQL 8.0.19); everything else rejects with error 1298
    - AES_ENCRYPT produces identical ciphertext on every server and matches PHP openssl aes-128-ecb, so encrypted data is fully portable
    - Result metadata through an aliased view: MySQL/Percona report the view's name in orgtable, MariaDB reports the query alias; neither reports the underlying base table
    - MEDIUMTEXT metadata charset varies by era (45 / 255 / 224) but is never binary (63), so MEDIUMBLOB encryption detection is safe everywhere
    - Consistent-snapshot backups: the SET TRANSACTION ISOLATION LEVEL REPEATABLE READ + START TRANSACTION WITH CONSISTENT SNAPSHOT pair holds a point-in-time snapshot on every server, survives statements between the SET and the START, needs no privileges, and reverts after COMMIT. A bare START at READ-COMMITTED never holds one: MySQL/Percona and MariaDB thru 10.5 warn (code 138), MariaDB 10.6+ says nothing, and with the RocksDB plugin loaded (no RocksDB table needed) MariaDB rejects it with error 4062 while Percona MyRocks only warns
    - SET TRANSACTION (next-transaction scope) throws error 1568 whenever a transaction is open, including autocommit=0 after any table read (autocommit=0 alone is fine); the SET SESSION form is accepted mid-transaction on every server
    - The isolation variable splits by vendor: @@transaction_isolation is missing on MariaDB thru 10.11 (added 11.1), @@tx_isolation is missing on MySQL/Percona 8.0+, and neither ever reports the pending one-shot level, so "did the snapshot take" is only observable behaviorally

    ## Probe results


    __SUMMARY__;

// Probe order follows first appearance across the reports
$probeNames = [];
foreach ($reports as $probes) {
    foreach ($probes as $name => $value) {
        $probeNames[$name] = true;
    }
}

foreach (array_keys($probeNames) as $name) {
    $serversByValue = [];
    $missing        = [];
    foreach ($reports as $server => $probes) {
        if (array_key_exists($name, $probes)) {
            $serversByValue[$probes[$name]][] = $server;
        } else {
            $missing[] = $server;
        }
    }

    echo "### $name\n\n";
    if (count($serversByValue) === 1 && !$missing) {
        echo "- all servers: " . mdValue((string)array_key_first($serversByValue)) . "\n";
    } else {
        foreach ($serversByValue as $value => $servers) {
            $group = serverGroupLabel($servers, $families) ?? implode(', ', $servers);
            echo "- " . mdValue((string)$value) . " → $group\n";
        }
        if ($missing) {
            $group = serverGroupLabel($missing, $families) ?? implode(', ', $missing);
            echo "- (no data) → $group\n";
        }
    }
    echo "\n";
}
