#!/usr/bin/env php
<?php
declare(strict_types=1);

/**
 * Merge the JSON files written by index-rules-probe.php --json into one markdown
 * report: one table per question, one row per server, one column per case. Error
 * and warning messages are listed in full under each table, with the servers that
 * produced them when the wording differs.
 *
 *     php .github/scripts/index-rules-merge.php probes/*.json
 *     php .github/scripts/index-rules-merge.php probes/*.json >> "$GITHUB_STEP_SUMMARY"
 *     php .github/scripts/index-rules-merge.php probes/*.json > docs/internal/index-rules-matrix.md
 */

require __DIR__ . '/ci-lib.php';

if ($argc < 2) {
    fwrite(STDERR, "Usage: php .github/scripts/index-rules-merge.php <probe.json> [probe2.json ...]\n");
    exit(1);
}

$reports = []; // server => report
foreach (array_slice($argv, 1) as $path) {
    $report = is_file($path) ? json_decode(file_get_contents($path), true) : null;
    if (isset($report['server'], $report['questions'])) {
        $reports[$report['server']] = $report;
    } else {
        fwrite(STDERR, "Skipping $path: not an index-rules-probe JSON file\n");
    }
}
uksort($reports, fn($a, $b) => databaseSortKey($a) <=> databaseSortKey($b));

if (!$reports) {
    echo "# Index Rules Matrix\n\nNo probe data found.\n";
    exit;
}

/**
 * One markdown cell for a case result. Errors show the code only; the message is
 * listed under the table.
 */
function cell(?array $r): string
{
    if ($r === null) {
        return 'n/a'; // case needs a server variable this server doesn't have (innodb_large_prefix)
    }
    if (!$r['ok']) {
        return (!empty($r['table_error']) ? 'CREATE TABLE ' : '') . "ERR $r[code]";
    }
    $parts = ['OK'];
    if (isset($r['sub_part'])) {
        $parts[] = "Sub_part=$r[sub_part]";
    }
    if (!empty($r['warnings'])) {
        $parts[] = 'warn ' . implode('+', array_map(fn($w) => explode(':', $w, 2)[0], $r['warnings']));
    }
    if (isset($r['using_filesort'])) {
        $parts[] = "key=$r[explain_key]";
        $parts[] = "filesort=$r[using_filesort]";
    }
    if (isset($r['note']) && !isset($r['sub_part'])) {
        $parts[] = mdValue($r['note']);
    }
    return implode(' ', $parts);
}

echo "# Index Rules Matrix\n\n";
echo "Does the prefix rule CMS Builder uses when it auto-creates an index hold on every supported server? ";
echo "The rule: TEXT/BLOB family always gets `(768)`, VARCHAR(n)/VARBINARY(n) gets `(min(n, 768))`, everything else gets no prefix. ";
echo "Generated by the \"Index Rules Matrix\" workflow (.github/workflows/index-rules-matrix.yml); regenerate with:\n\n";
echo "    gh workflow run index-rules-matrix.yml   # wait for the run to finish, then:\n";
echo "    gh run download --dir probes             # pick the latest Index Rules Matrix run\n";
echo "    php .github/scripts/index-rules-merge.php probes/*/index-probe-*.json > docs/internal/index-rules-matrix.md\n\n";
echo "Last generated: " . date('Y-m-d') . " from " . count($reports) . " servers. Generated file - don't hand-edit.\n\n";
// Curated verdicts - update by hand when the probe data changes
echo <<<__VERDICTS__
    ## Verdicts

    1. **Key length required.** Every MySQL/Percona and MariaDB thru 10.3 reject a no-prefix index on all eight TEXT/BLOB types with error 1170. MariaDB 10.4+ accepts it and picks the prefix itself: 255 for TINYTEXT/TINYBLOB, 768 for TEXT/MEDIUMTEXT/LONGTEXT, 3072 for BLOB/MEDIUMBLOB/LONGBLOB, with warning 1071 on the 768 and 3072 cases. The CMS rule (always add a prefix) is required on the first group and harmless on the second.
    2. **Prefix longer than the column.** `(768)` on TINYTEXT or TINYBLOB fails on every MySQL/Percona with error 1071 "max key length is 255 bytes"; every MariaDB accepts it and reports Sub_part=255. `(255)` on TINYTEXT also fails on MySQL/Percona (255 chars x 4 bytes is over the 255-byte column). `(63)` on TINYTEXT and `(255)` on TINYBLOB work everywhere. The CMS rule is wrong for the TINY types on MySQL/Percona: use TINYTEXT `(63)` and TINYBLOB `(255)`.
    3. **VARCHAR prefix equal to the column length.** `(255)` on VARCHAR(255) is a whole-column index on every server: SHOW INDEX reports Sub_part NULL, SHOW CREATE TABLE prints the key without a prefix, and ORDER BY uses the index with no filesort, same as no prefix. `(250)` is a real prefix index and ORDER BY filesorts. The CMS rule holds: `min(n, 768)` with n at or below 768 gives a whole-column index.
    4. **Where the cap is.** 768 utf8mb4 characters and 3072 bytes are the limits on every server for ROW_FORMAT=DYNAMIC. Past the cap, MySQL/Percona and MariaDB 10.2.6/10.2.7 fail with error 1071; MariaDB 10.2.44 and 10.3+ create the index anyway, cut to 768 or 3072, with warning 1071. The CMS rule holds. (VARBINARY could go to 3072; `min(n, 768)` is only conservative there.)
    5. **Other row formats.** COMPACT and REDUNDANT cap at 767 bytes (191 utf8mb4 characters) on every server, so VARCHAR(768) with no prefix and TEXT `(768)` both fail: MySQL/Percona error 1071 "max key length is 767 bytes", MariaDB error 1709 "Index column size too large. The maximum column size is 767 bytes" (not 1071). innodb_large_prefix is ON by default on MySQL/Percona 5.7 and MariaDB 10.2; set OFF, DYNAMIC caps at 767 bytes too (5.7 fails with 1071; MariaDB 10.2.44 truncates to 191 with a warning). MariaDB 10.3-10.5 show the variable as read-only and empty; it is gone in MariaDB 10.6+ and MySQL 8.0+. The CMS rule assumes DYNAMIC; on a COMPACT or REDUNDANT table (the MySQL 5.6 default) 768 fails everywhere and 191 is the limit.
    6. **Types that can't take a plain index.** CHAR(255), BINARY(255), ENUM, SET, DECIMAL(10,2), DATETIME index with no prefix on every server. JSON: MySQL/Percona error 3152 on every version (wording differs 5.7 vs 8.0+); MariaDB 10.2.7 thru 10.3 treat it as LONGTEXT and give 1170; MariaDB 10.2.6 has no JSON type (1064 at CREATE TABLE); MariaDB 10.4+ auto-prefix to 768 with warning 1071. GEOMETRY: error 1170 on MySQL/Percona 5.7 and MariaDB thru 10.3; MySQL/Percona 8.0+ turn it into a SPATIAL index attempt and fail with 1252 "All parts of a SPATIAL index must be NOT NULL"; MariaDB 10.4+ auto-prefix to 3072 with warning 1071. The CMS rule holds for the six ordinary types; JSON and GEOMETRY need their own handling on MySQL/Percona.
    7. **Case.** Lowercase `tinytext` behaves exactly like `TINYTEXT` on every server, and SHOW CREATE TABLE prints the type lowercase on every server (MariaDB adds `DEFAULT NULL`).


    __VERDICTS__;

echo "Cells: `OK Sub_part=N` means CREATE INDEX succeeded and SHOW INDEX reports that prefix (NULL = whole column indexed). ";
echo "`warn` lists warning codes a successful CREATE INDEX raised. `ERR n` is the MySQL error code; messages are under each table.\n\n";

//
// Server settings
//
$settingNames = array_keys(reset($reports)['identity']);
echo "## Server settings\n\n| server | " . implode(' | ', $settingNames) . " |\n|---|" . str_repeat('---|', count($settingNames)) . "\n";
foreach ($reports as $server => $report) {
    echo "| $server | " . implode(' | ', array_map(fn($k) => mdValue((string)($report['identity'][$k] ?? '(missing)')), $settingNames)) . " |\n";
}
echo "\n";

//
// One table per question
//
$questionTitles = [];
foreach ($reports as $report) {
    foreach (array_keys($report['questions']) as $title) {
        $questionTitles[$title] = true;
    }
}

foreach (array_keys($questionTitles) as $title) {
    // Column order: cases in the order the probe ran them, union across servers
    $caseNames = [];
    foreach ($reports as $report) {
        foreach (array_keys($report['questions'][$title] ?? []) as $case) {
            $caseNames[$case] = true;
        }
    }
    $caseNames = array_keys($caseNames);

    echo "## $title\n\n| server | " . implode(' | ', $caseNames) . " |\n|---|" . str_repeat('---|', count($caseNames)) . "\n";
    $messages = []; // "code: message" => [servers]
    $byCase   = []; // case => cell => [servers]
    foreach ($reports as $server => $report) {
        $cells = [];
        foreach ($caseNames as $case) {
            $r       = $report['questions'][$title][$case] ?? null;
            $cells[] = cell($r);
            if ($r !== null) {
                $byCase[$case][cell($r)][] = $server;
            }
            if ($r !== null && !$r['ok']) {
                $messages["$r[code]: $r[error]"][] = $server;
            }
            foreach ($r['warnings'] ?? [] as $w) {
                $messages["warning $w"][] = $server;
            }
        }
        echo "| $server | " . implode(' | ', $cells) . " |\n";
    }
    echo "\n";

    // Agreement summary per column
    $families = serverFamilies(array_keys($reports));
    foreach ($caseNames as $case) {
        $groups = $byCase[$case];
        $ran    = count(array_merge(...array_values($groups)));
        $scope  = $ran === count($reports) ? 'every server' : "every server that ran it ($ran)";
        if (count($groups) === 1) {
            echo "- **$case**: $scope: " . array_key_first($groups) . "\n";
            continue;
        }
        $parts = [];
        foreach ($groups as $value => $servers) {
            $parts[] = "$value (" . (serverGroupLabel($servers, $families) ?? implode(', ', $servers)) . ")";
        }
        echo "- **$case**: SPLIT: " . implode('; ', $parts) . "\n";
    }
    echo "\n";

    if ($messages) {
        echo "Messages:\n\n";
        foreach ($messages as $message => $servers) {
            $servers = array_values(array_unique($servers));
            $who     = count($servers) === count($reports) ? 'all' : (serverGroupLabel($servers, $families) ?? implode(', ', $servers));
            echo "- " . mdValue($message) . " ($who)\n";
        }
        echo "\n";
    }

    // Notes (EXPLAIN detail), grouped by identical text
    $notes = [];
    foreach ($reports as $server => $report) {
        foreach ($caseNames as $case) {
            $note = $report['questions'][$title][$case]['note'] ?? null;
            if ($note !== null && isset($report['questions'][$title][$case]['sub_part'])) {
                $notes[$case][$note][] = $server;
            }
        }
    }
    if ($notes) {
        echo "Notes:\n\n";
        foreach ($notes as $case => $byNote) {
            foreach ($byNote as $note => $servers) {
                $who = count($servers) === count($reports) ? 'all' : (serverGroupLabel($servers, $families) ?? implode(', ', $servers));
                echo "- $case: " . mdValue($note) . " ($who)\n";
            }
        }
        echo "\n";
    }

    // SHOW CREATE TABLE lines, only where servers print them differently
    $createLines = [];
    foreach ($reports as $server => $report) {
        foreach ($caseNames as $case) {
            $line = $report['questions'][$title][$case]['show_create'] ?? null;
            if ($line !== null) {
                $createLines[$case][$line][] = $server;
            }
        }
    }
    $splitLines = array_filter($createLines, fn($byLine) => count($byLine) > 1);
    if ($splitLines) {
        echo "SHOW CREATE TABLE differs:\n\n";
        foreach ($splitLines as $case => $byLine) {
            foreach ($byLine as $line => $servers) {
                echo "- $case: " . mdValue($line) . " (" . (serverGroupLabel($servers, $families) ?? implode(', ', $servers)) . ")\n";
            }
        }
        echo "\n";
    }
}
