#!/usr/bin/env php
<?php
declare(strict_types=1);

/**
 * Merge the JSON files written by db-behavior-report.php --json into one markdown
 * comparison. Identical answers collapse to one line per probe, so the report reads
 * as "who differs" instead of a per-server grid.
 *
 *     php tools/db-behavior-merge.php reports/*.json
 *     php tools/db-behavior-merge.php reports/*.json >> "$GITHUB_STEP_SUMMARY"
 *     php tools/db-behavior-merge.php reports/<artifact>/report-*.json > tools/db-behavior-report.md
 */

require __DIR__ . '/ci-lib.php';

if ($argc < 2) {
    fwrite(STDERR, "Usage: php tools/db-behavior-merge.php <report.json> [report2.json ...]\n");
    exit(1);
}

// server => [probe => value], ordered mysql, mariadb, percona, each oldest version first
$reports = [];
foreach (array_slice($argv, 1) as $path) {
    $report = is_file($path) ? json_decode(file_get_contents($path), true) : null;
    if (isset($report['server'], $report['probes'])) {
        $reports[$report['server']] = $report['probes'];
    } else {
        fwrite(STDERR, "Skipping $path: not a db-behavior-report JSON file\n");
    }
}
uksort($reports, fn($a, $b) => databaseSortKey($a) <=> databaseSortKey($b));

if (!$reports) {
    echo "# DB Behavior Report\n\nNo probe data found.\n";
    exit;
}

$families = serverFamilies(array_keys($reports));

echo "# DB Behavior Report\n\n";
echo "How every supported database server answers the same behavior probes, showing only where servers disagree. ";
echo "Generated by the \"DB Behavior Report\" workflow (.github/workflows/db-behavior-report.yml); regenerate with:\n\n";
echo "    gh workflow run db-behavior-report.yml   # wait for the run to finish, then:\n";
echo "    gh run download --dir reports            # pick the latest DB Behavior Report run\n";
echo "    php tools/db-behavior-merge.php reports/*/report-*.json > tools/db-behavior-report.md\n\n";
echo "Last generated: " . date('Y-m-d') . " from " . count($reports) . " servers: " . implode(', ', array_keys($reports)) . "\n\n";
echo "Stock Docker images with default configs answered these probes. Install-dependent rows ";
echo "(directory paths, sql_mode, TLS and log settings, version strings) will differ on real servers, ";
echo "where distro packages, hosting panels, and my.cnf all change them. SHOW CREATE formatting, ";
echo "error codes, collations, and result typing are fixed per server version.\n\n";

// Curated summary - update by hand when the probe data changes
echo <<<__SUMMARY__
    ## Key differences

    - Percona Server answers every probe byte-identically to the same MySQL version; it never needs separate handling
    - TLS: session status Ssl_cipher/Ssl_version exist on every server and are empty exactly when the connection is unencrypted - the only signal that works everywhere. The variables all have holes: @@have_ssl was removed in MySQL/Percona 8.4 and reads DISABLED on stock MariaDB thru 10.11 but YES on MariaDB 11.4+ (auto-generated certs); @@tls_version is missing on MariaDB thru 10.3; @@require_secure_transport is missing on MariaDB thru 10.4
    - Every version source agrees: server_info matches VERSION() byte-for-byte, and mysqlnd's server_version int matches to the patch level (Percona's build suffix dropped correctly) - though that int is a client-side parse, and PHP before 8.0.16/8.1.3 misread MariaDB's `5.5.5-` handshake prefix as 50505 (php-src GH-7972)
    - SHOW CREATE splits by vendor: MySQL quotes defaults (`'0'`) and prints `CURRENT_TIMESTAMP`; MariaDB prints typed literals (`0`) and `current_timestamp()`, and keeps int display widths (`int(11)`) that MySQL 8.0+ dropped
    - CHECK constraints are parsed but silently ignored on MySQL/Percona 5.7; enforced everywhere else, with different error codes (MySQL 3819, MariaDB 4025) and different SHOW CREATE placement (MySQL hoists column CHECKs into named constraints, MariaDB keeps them inline)
    - CHECK lifecycle splits: ADD CONSTRAINT / DROP CONSTRAINT is the one add/drop pair every 8.0.16+ and MariaDB server accepts (DROP CHECK and NOT ENFORCED are MySQL-only). MODIFY COLUMN with an inline CHECK accumulates duplicate auto-named constraints on MySQL 8.0+ but replaces the column's CHECK on MariaDB, where it also can't be dropped by name. Renaming a column a CHECK references is rejected on MySQL 8.0+ (error 3959) but auto-rewrites the expression on MariaDB; DROP COLUMN silently deletes a single-column CHECK on both
    - Default utf8mb4 collation splits four ways: none stated (5.7 era), 0900_ai_ci (MySQL/Percona 8.0+), general_ci (MariaDB 10.4-10.11), uca1400_ai_ci (MariaDB 11.4+)
    - MariaDB 11.4+ lists temporary tables in SHOW TABLES and INFORMATION_SCHEMA.TABLES; every other server hides them
    - Bare TIMESTAMP columns get implicit DEFAULT CURRENT_TIMESTAMP ON UPDATE on MySQL/Percona 5.7 and MariaDB thru 10.6, but stay plain nullable on MySQL/Percona 8.0+ and MariaDB 10.11+ (explicit_defaults_for_timestamp default changed)
    - Time zone offsets beyond -12:59..+13:00 are accepted only by MySQL/Percona 8.0+ (widened in MySQL 8.0.19); everything else rejects with error 1298
    - AES_ENCRYPT produces identical ciphertext on every server and matches PHP openssl aes-128-ecb, so encrypted data is fully portable
    - Result metadata through an aliased view: MySQL/Percona report the view's name in orgtable, MariaDB reports the query alias; neither reports the underlying base table
    - MEDIUMTEXT metadata charset varies by era (45 / 255 / 224) but is never binary (63), so MEDIUMBLOB encryption detection is safe everywhere

    ## Probe results


    __SUMMARY__;

// Probe order follows first appearance across the reports
$probeNames = [];
foreach ($reports as $probes) {
    foreach ($probes as $name => $value) {
        $probeNames[$name] = true;
    }
}

foreach (array_keys($probeNames) as $name) {
    $serversByValue = [];
    $missing        = [];
    foreach ($reports as $server => $probes) {
        if (array_key_exists($name, $probes)) {
            $serversByValue[$probes[$name]][] = $server;
        } else {
            $missing[] = $server;
        }
    }

    echo "### $name\n\n";
    if (count($serversByValue) === 1 && !$missing) {
        echo "- all servers: " . mdValue((string)array_key_first($serversByValue)) . "\n";
    } else {
        foreach ($serversByValue as $value => $servers) {
            $group = serverGroupLabel($servers, $families) ?? implode(', ', $servers);
            echo "- " . mdValue((string)$value) . " → $group\n";
        }
        if ($missing) {
            $group = serverGroupLabel($missing, $families) ?? implode(', ', $missing);
            echo "- (no data) → $group\n";
        }
    }
    echo "\n";
}
